[project]
name = "yuhang"
version = "0.1.0"
requires-python = ">=3.12, <3.13"  # ← 关键修改！
dependencies = [
    "accelerate",
    "colorlog",
    "datasets",
    "editdistance",
    "evaluate",
    "fire",
    "FlagEmbedding",
    "huggingface-hub",
    "langchain",
    "langgraph",
    "llmlingua",
    "loguru",
    "matplotlib",
    "modelscope",
    "mteb",
    "openai",
    "peft",
    "sentence-transformers",
    "tiktoken",
    "torch",
    "transformers",
    "tree-sitter",
    "tree-sitter-go",
    "tree-sitter-java",
    "tree-sitter-python",
    "vllm",
]

[tool.uv.workspace]
members = ["LongCodeZip"]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
longcodezip = { workspace = true }
